# Generated by Django 5.1.5 on 2025-02-05 15:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Генеральний директор'), ('deputy_director', 'Заступник директора'), ('manager', 'Менеджер'), ('foreman', 'Прораб'), ('chief_estimator', 'Начальник кошторисного відділу'), ('estimator', 'Кошторисник'), ('chief_accountant', 'Головний бухгалтер'), ('accountant', 'Бухгалтер'), ('chief_engineer', 'Головний інженер'), ('engineer', 'Інженер ПТО'), ('chief_economist', 'Головний економіст'), ('economist', 'Економіст'), ('chief_lawyer', 'Головний юрист'), ('lawyer', 'Юрист'), ('chief_supply', 'Начальник відділу постачання'), ('supply_specialist', 'Фахівець відділу постачання')], max_length=30, verbose_name='Посада')),
                ('birthday', models.DateField(verbose_name='День народження')),
                ('mobile_phone', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^+\\d{12}$', 'Введіть номер телефону з +38..')], verbose_name='Номер мобільного телефону')),
                ('internal_phone', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Введіть номер внутрішнього телефону.')], verbose_name='Номер внутрішнього телефону')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Працівник')),
            ],
            options={
                'verbose_name_plural': 'employees',
            },
        ),
    ]
