# Generated by Django 5.1.5 on 2025-02-06 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\+\\d{12}$', 'Введіть номер телефону з +38..')], verbose_name='Номер мобільного телефону'),
        ),
    ]
