# Generated by Django 5.1.5 on 2025-02-06 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0002_alter_employee_mobile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='accountant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_projects', to='users.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='economist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='economist_projects', to='users.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_projects', to='users.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='estimator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimator_projects', to='users.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='foreman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreman_projects', to='users.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_projects', to='users.employee'),
        ),
    ]
