# Generated by Django 5.1.5 on 2025-02-03 11:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Повне найменування організації')),
                ('edrpou', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'ЄДРПОУ повинен містити рівно 8 цифр.')], verbose_name='ЄДРПОУ')),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='Номер договору №:')),
                ('date_signing', models.DateField(verbose_name='Дата підписання договору')),
                ('date_completion', models.DateField(verbose_name='Дата завершеня договору')),
                ('customer_contract_name', models.CharField(choices=[('Замовник', 'Замовник'), ('Підрядник', 'Підрядник'), ('Виконавець', 'Виконавець'), ('Генпідрядник', 'Генпідрядник'), ('Генеральний підрядник', 'Генеральний підрядник'), ('Субпідрядник', 'Субпідрядник')], max_length=21, unique=True, verbose_name='Найменування Замовника за договором')),
                ('contractor_contract_name', models.CharField(choices=[('Замовник', 'Замовник'), ('Підрядник', 'Підрядник'), ('Виконавець', 'Виконавець'), ('Генпідрядник', 'Генпідрядник'), ('Генеральний підрядник', 'Генеральний підрядник'), ('Субпідрядник', 'Субпідрядник')], max_length=21, unique=True, verbose_name='Найменування Підрядника за договором')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Сума договору')),
                ('subject_contract', models.CharField(max_length=1500, verbose_name='Предмет договору')),
                ('shot_subject_contract', models.CharField(blank=True, max_length=200, null=True, verbose_name='Коротка назва')),
                ('address', models.CharField(max_length=300, verbose_name='Адреса об`єкту')),
                ('type', models.CharField(choices=[('ГП', 'Генпідрядний'), ('СП', 'Субпідрядний')], default='ГП', max_length=15, verbose_name='Тип договору')),
                ('contractor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_contractor', to='estimation.company', verbose_name='Підрядник')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_customer', to='estimation.company', verbose_name='Замовник')),
            ],
            options={
                'verbose_name_plural': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Січень', 'Січень'), ('Лютий', 'Лютий'), ('Березень', 'Березень'), ('Квітень', 'Квітень'), ('Травень', 'Травень'), ('Червень', 'Червень'), ('Липень', 'Липень'), ('Серпень', 'Серпень'), ('Вересень', 'Вересень'), ('Жовтень', 'Жовтень'), ('Листопад', 'Листопад'), ('Грудень', 'Грудень')], max_length=15, verbose_name='Період будівництва')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Номер акту')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата підписання акту')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Сума акту')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Заробітна плата в акті')),
                ('man_hours', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Трудовитрати')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Примітка до акту')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='estimation.contract', verbose_name='Договір')),
            ],
            options={
                'verbose_name_plural': 'acts',
            },
        ),
    ]
