# Generated by Django 5.1.5 on 2025-02-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='customer',
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ManyToManyField(related_name='contracts_as_contractor', to='estimation.company', verbose_name='Підрядник'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ManyToManyField(related_name='contracts_as_customer', to='estimation.company', verbose_name='Замовник'),
        ),
    ]
