# Generated by Django 5.1.5 on 2025-02-03 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0002_remove_contract_contractor_remove_contract_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contractor',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractor_contract_name',
            field=models.CharField(choices=[('Замовник', 'Замовник'), ('Підрядник', 'Підрядник'), ('Виконавець', 'Виконавець'), ('Генпідрядник', 'Генпідрядник'), ('Генеральний підрядник', 'Генеральний підрядник'), ('Субпідрядник', 'Субпідрядник')], max_length=21, verbose_name='Найменування Підрядника за договором'),
        ),
        migrations.RemoveField(
            model_name='contract',
            name='customer',
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_contract_name',
            field=models.CharField(choices=[('Замовник', 'Замовник'), ('Підрядник', 'Підрядник'), ('Виконавець', 'Виконавець'), ('Генпідрядник', 'Генпідрядник'), ('Генеральний підрядник', 'Генеральний підрядник'), ('Субпідрядник', 'Субпідрядник')], max_length=21, verbose_name='Найменування Замовника за договором'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Номер договору №:'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_contractor', to='estimation.company', verbose_name='Підрядник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_customer', to='estimation.company', verbose_name='Замовник'),
            preserve_default=False,
        ),
    ]
