# Generated by Django 5.1.5 on 2025-02-06 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0004_act_year'),
        ('projects', '0002_project_accountant_project_economist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'verbose_name': 'act', 'verbose_name_plural': 'acts'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='shot_subject_contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projects.project', verbose_name='Назва проекту'),
            preserve_default=False,
        ),
    ]
