# Generated by Django 5.1.5 on 2025-02-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0006_addendum'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[(True, 'Активний'), (False, 'Завершений')], default=True, max_length=21, verbose_name='Статус договору'),
            preserve_default=False,
        ),
    ]
