# Generated by Django 5.1.5 on 2025-02-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0008_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(choices=[(True, 'Активний'), (False, 'Завершений')], verbose_name='Статус договору'),
        ),
    ]
