# Generated by Django 5.1.5 on 2025-02-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0010_alter_contract_status'),
        ('projects', '0002_project_accountant_project_economist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адреса об`єкту'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='shot_subject_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project', verbose_name='Назва проекту'),
        ),
    ]
